### PR TITLE
244 overview to mermaidjs

### PR DESCRIPTION
**Pull request by chrishalbert**
## Pull Request
Addresses: https://github.com/shipt/opsml/issues/244

### Short Summary
This illustrates the potential using mermaidjs.

### Context
This can be reworked to your liking/desire. Right now, its using the default themes, however, they can be customized. There are some constraints though that may make this a less desirable option, but I'll leave that up to the maintainers :)

### Constraints:
* **Mermaid Version** - Github isn't supporting `mermaid.js` 10.1.0 yet, which means you can't do format the text with **bold** or _italics_. 
* **Colors** - You can theme primary/secondary/tertiary colors, however, it doesn't _seem_ like you can create more than one theme, or class definition - so your entities can't be different colors or at least that's what it seems like right now. You may be able to define a few themes, but I didn't have any luck and it seemed like it was getting a little verbose for that feature so I was going to leave that up to you all.
* **Shapes** - You are limited here, so I made a judgement call on the interface.

I'm not a designer by any means - I just like coding and diagrams, but if you all are ok with these limitations, I can add to this or create another one working against one of the more complex diagrams. 

### Is this a Breaking Change?
No!

### CODE REVIEW

**Comment by chrishalbert** [comment]
@thorrester - The build is failing due to a missing gitleaks key, which I'm guessing is restricted by organization. What would you suggest to move forward? Also - nice work on the mermaid additions in https://github.com/shipt/opsml/pull/243/ ! - I didn't see the `style` definitions documented anywhere, but I can update this PR similarly - just let me know. Thanks!

**Comment by chrishalbert** [comment]
Right on, thanks for the set of :eyes:! I know this pr is a trivial add right now, but hopefully, I'll be able to provide some more substantial contributions in the future.

**Comment by thorrester** [comment]
@chrishalbert - when you get a chance, could you update your fork with `main` and re-commit? I updated the workflows on main, so I think the PR should work now

**Comment by chrishalbert** [comment]
It looks like we've gotten further! https://github.com/shipt/opsml/actions/runs/7660996561/job/20879504316?pr=247#step:2:431

**Comment by thorrester** [comment]
Looks like we still need to play around with the gitleaks workflow, but the PR is good!

**Review by thorrester — APPROVED** [review]

**Comment by chrishalbert** [comment]
Awesome! Is it ok if I create a separate Issue/PR for => https://thorrester.github.io/opsml-ghpages/cards/overview/ , or how would you prefer I work on those conversions incrementally?

**Comment by thorrester** [comment]
Yea, Let's keep the issue open, and then you can create another PR. I'll go ahead and merge this in. Thanks again for the contribution!

**Pull request merged**
